# Generated by Django 2.1.7 on 2019-02-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['make'], 'permissions': (('AutoFullAccess', 'Can do CRUD on auto'), ('AutoReadOnly', 'Can read all auto data, but not modifying them'))},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ['name'], 'permissions': (('MakeFullAccess', 'Can do CRUD on make'), ('MakeReadOnly', 'Can read all make data, but not modifying them'))},
        ),
    ]
