# Generated by Django 2.1.7 on 2019-02-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20190220_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ['make'], 'permissions': (('AutoFullAccess', 'Full access: can do CRUD on auto'), ('AutoReadOnly', 'Read only: can read all auto data, but not modifying them'))},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ['name'], 'permissions': (('MakeFullAccess', 'Full access: can do CRUD on make'), ('MakeReadOnly', 'Read only: can read all make data, but not modifying them'))},
        ),
    ]
