# Generated by Django 2.1.7 on 2019-02-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190201_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_edit_delete', 'Can do CRUD for authors'),)},
        ),
    ]
