# Generated by Django 2.1.7 on 2019-02-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190212_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_edit_delete_author', 'Can do CRUD to any author'),)},
        ),
    ]
