# Generated by Django 2.1.7 on 2019-03-01 18:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')])),
                ('population', models.PositiveIntegerField()),
                ('slogan', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['nickname'],
                'permissions': (('CityFullAccess', 'Full access: can do CRUD on city'), ('CityReadOnly', 'Read only: can read all city data, but not modifying them')),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'State must be greater than 1 character')])),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('StateFullAccess', 'Full access: can do CRUD on state'), ('StateReadOnly', 'Read only: can read all state data, but not modifying them')),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='citys.State'),
        ),
    ]
