# Generated by Django 2.1.7 on 2019-02-23 21:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Breed must be greater than 1 character')])),
            ],
            options={
                'ordering': ['name'],
                'permissions': (('BreedFullAccess', 'Full access: can do CRUD on breed'), ('BreedReadOnly', 'Read only: can read all breed data, but not modifying them')),
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Nickname must be greater than 1 character')])),
                ('weight', models.PositiveIntegerField()),
                ('foods', models.CharField(max_length=300)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.Breed')),
            ],
            options={
                'ordering': ['nickname'],
                'permissions': (('CatFullAccess', 'Full access: can do CRUD on cat'), ('CatReadOnly', 'Read only: can read all cat data, but not modifying them')),
            },
        ),
    ]
